# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc77002e728d1a1cd998cdad264c5476c3f81c28f69846bb2ce930e399dfdff536fc3a946cc5479cc1398219fe0fe192d68f8c7fa995a8ee965335b8fc6419bd

test:
  secret_key_base: e75f942c3bcead3a0d5df4432b06d65d9460aee9ccf43365a896f05d576cc66eae6fed06e71b6c95ab65eaa7812655dab5384fbf6ddda01a56c74ea1bf4ab323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
